### PR TITLE
Upgrade to v4.16.0

### LINKED ISSUE #48: Upgrade to 4.15.1 to patch security vulnerabliity
### Security vulnerability

Ghost has found and fixed a breach that allowed unauthenticated email users to change the email addresses of arbitrary member accounts. Details can be found [here](https://github.com/TryGhost/Ghost/security/advisories/GHSA-65p7-pjj8-ggmr).

### Affected versions

The vulnerability affects Ghost versions between 3.18.0 and 4.15.0 (inclusive), which includes the version of Ghost used in this repo (4.9.1). We should upgrade this to the patched version, 4.15.1, as soon as possible so that YunoHost users can be protected too.

### Solutions

Upgrade to the patched version of Ghost, 4.15.1

**As a temporary measure:** before upgrading, one can block the `POST /members/api/send-magic-link/` endpoint—but this is not recommended as it would also block legitimate members from logging in and signing up on the site. I'm not very good at nginx configuration, but if someone could paste instructions on how to do this, that would help!

### PR DESCRIPTION
**Pull request by tituspijean**
Closes #48 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
[Test Badge](https://ci.pijean.ovh/ci/job/46)

**Review by ericgaspar — APPROVED** [review]

**Comment by eauchat** [comment]
Wow that was fast reaction to an issue 👍
Just to understand how yunohost works on the app update side, what will trigger yunohost to notice there is an upgrade? This is merged so I was expecting the upgrade to be available in yunohost directly, but somehow it is not yet.

**Comment by tituspijean** [comment]
I have a *slight* doubt, but I think the catalog is updated twice a day during the diagnosis. However, by default, you have to manually run the update from the webadmin and select the apps to upgrade (or `yunohost tools update` then `yunohost tools upgrade apps`). There is the "Unattented upgrades" app to have it performed on a regular basis. 😉

**Comment by eauchat** [comment]
Ok, then I guess what I didn't know about was the catalog part.
I was trying to install another app in which I just merged some modifications to the master branch, but the webadmin didn't seem to see the recent changes, unless I'd pass the app repository directly. Now I understand that I should wait for the catalog update for the webadmin to see the modifications.
Thanks @tituspijean :)

**Pull request merged**
