### PR TITLE
Update to 3.38.2

### PR DESCRIPTION
**Pull request by steakscience**
## Problem
- Update to the latest version (3.38.2)

## Solution
- Updated relevant files

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check. ---> I don't have a Debian computer, need someone to test
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/ghost_ynh%20PR24%20(yalh76)/)

### CODE REVIEW

**Comment by steakscience** [comment]
@yalh76 Please see if this is done correctly! Thanks!

**Review by yalh76 — APPROVED** [review]
Great work ;)

**Review by yalh76 — CHANGES_REQUESTED** [review]
Would be cool to add a test upgrade from current version for package_check and launch a package_check on your PR ;)

**Comment by steakscience** [comment]
@yalh76 I've tested upgrading, it worked fine. However, I cannot do anything with package_check since I don't have a Debian computer

**Pull request merged**
