### PR TITLE
Fixes and upgrade to v5.8.3

### LINKED ISSUE #163: Version 5.0 Is missing?
### Describe the bug

*5.2.2~ynh1 of GHOST is still on the v4.48.0*

### Context

- Hardware: *Linode Server*
- YunoHost version: 4.3.6.3 (stable)
- I have access to my server: *Through SSH & through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 5.2.2~ynh1

### Steps to reproduce

- *If the error occurs in your browser, explain what you did:*
   1. *Go to Yunohost Admin page, then to  Applications, find 'Ghost', and Install* & or *Go to System Update, Upgrade Ghost 4.48.0 (your current Version) to 5.2.2*
   3. *Go to Ghost Admin page, sign up/sign in and proceed into Admin Dashboard*
   4. *Top of screen has a error alert that you are not on Ghost 5.0*
   5. *Looking for new 5.0 features that did not exist in previous versions and are missing in 5.2.2, such as NEW DASHBOARD.

### Attempts to solve (ALL FAILED)

1. Restart Server from Yunohost panel 
2. Install a new Ghost instance
3. Upgrade Primary Ghost instance
4. Upgrade Pre-production Ghost Instance

### Expected behavior

*Upgrade/Install to Ghost 5.2.2 and expect to see the new admin dashboard featured in Version 5.0, as well as other features like multiple newsletters.*

### Logs

5.48 TO 5.2.2 LOG (https://paste.yunohost.org/raw/fafirakece)

NEW INSTALLATION LOG https://paste.yunohost.org/raw/legabazoso

### PR DESCRIPTION
**Pull request by tituspijean**
Closes #163 and update app.src for v5.2.2

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Comment by tituspijean** [comment]
Incoming fixes:
- [ ] app.src data is now in subdir
- [ ] include theme in `content/themes/casper`

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Admin needs to be built.

**Comment by gcmtnskr** [comment]
> Admin needs to be built, any help is welcome.

Wish I could help, by no means am I coder.

**Comment by badrihippo** [comment]
What do you mean by "admin needs to be built", exactly? I can't promise much time, but I have been waiting for a while, so if you give me the details I might give it a shot when I have a free moment...

**Comment by tituspijean** [comment]
Basically we need to follow Ghost installation steps (cf. their documentation) to install it from source. However, it seems the administration panel of Ghost is not properly built. I get no errors, but the admin (accessible at `.../ghost` in the browser) does not load due to a missing template file.

**Comment by badrihippo** [comment]
Ah, okay. No guarantees on timing, but I'll take a look and see what I can do...

**Comment by badrihippo** [comment]
Okay, I see what you mean! I get an error page saying `Bad Request` when I try to load the admin. I've got a YunoHost dev env set up on my system now (LXC for the win!) so I'll try and play around with this again tomorrow.

**Comment by badrihippo** [comment]
@tituspijean is there a reason you're manually downloading ZIP files instead of doing a git recursive clone like they suggest? I suspect that might be the problem because of a couple of posts on the forums. If there's no specific reason, I can try switching to a git recursive clone and see if that works better.

**Comment by tituspijean** [comment]
Please do try and feel free to open a PR. :) I am a bit offline right now, I will have a look next week.

**Comment by badrihippo** [comment]
Okay, it seems to be working! They've moved around their structure quite a bit, so I updated the paths and switched to using the official `yarn` commands instead of directly calling scripts. Another thing to note is that the `Admin` package is now bundled along with the rest of Ghost so we don't have to pull it separately (we still do have to pull `Casper` though).

I'll test it out properly tomorrow and then attach a PR.

By the way, for the future, would it make more sense to have our scripts use the official `ghost` command-line tool to manage instances instead of manually installing like we're doing now? I can probably write up some logic to install `@tryghost/cli` for the first instance and then use the existing installation to manage subsequent instances. (@tituspijean if this sounds good to you I'll create a separate issue for it so we can flesh out the details!)

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
> By the way, for the future, would it make more sense to have our scripts use the official ghost command-line tool to manage instances instead of manually installing like we're doing now? I can probably write up some logic to install @tryghost/cli for the first instance and then use the existing installation to manage subsequent instances. (@tituspijean if this sounds good to you I'll create a separate issue for it so we can flesh out the details!)

That would be great! I'm not sure if it's possible to seamlessly transition from a manual install to a CLI one (the CLI yelled at me last time I tried), but feel free to investigate! ❤️

**Pull request merged**
