### PR TITLE
Fixed the app to work with YunoHost 3

### PR DESCRIPTION
**Pull request by anmol26s**
The packaging is not perfect, but works with YunoHost 3. Updating of the app works but need more testing.

### CODE REVIEW

**Comment by anmol26s** [comment]
@julienmalik 
Can you review and merge please?

**Comment by frju365** [comment]
Ok. This app is set as unmaintained. @anmol26s, do you want to maintain this app ? (I will surely maintain it with you)

**Comment by frju365** [comment]
cf. https://github.com/YunoHost-Apps/ghost_ynh/issues/8#issuecomment-272872272

**Comment by frju365** [comment]
Reviewed and validated in production.

**Comment by anmol26s** [comment]
Sorry for late reply. I was not well. I will maintain this app.

**Pull request merged**
