### PR TITLE
Update to v5.8.3 and use new install format

### PR DESCRIPTION
**Pull request by badrihippo**
## Problem

Ghost has significantly changed their file structure, which means the earlier build process was broken and the scripts had to be changed around quite a bit. (This commit builds upon the work by @tituspijean in #164)

~~:warning: **The upgrade process is completely untested!** Don't upgrade to this version unless you know what you are doing.~~ **update:** I've manually tested the update process now and it seems to be working :grin:

## Solution

Significant changes for the new build process are:

  - Config and content now lives under ./ghost/core instead of being directly in the project root. While updating, for
    backward compatibility, we need to check for the existence of the old folder as well
  - The admin interface is bundled along with the main Ghost package, so there is no need to download it separately (Casper is still being downloaded separately though)
  - Using `yarn setup` because manually running knex, grunt, etc. was causing problems (`yarn setup` automatically calls those commands for us behind the scenes)
 - Similarly, we are now running `yarn start` to execute the Ghost process in the systemd config, instead of manually running index.js` as we were doing earlier.

I think that sums up all the changes. Hopefully nothing else crops up!

## PR Status

- [x] Code finished and ready to be reviewed/tested
  - [x] Changing the config and content location
  - [x] No separate download of the admin interface
  - [x] Successful build process
  - [x] Successful start after Ghost installed
- [x] The fix/enhancement were manually tested (if applicable)
  - [x] Successful fresh installation
    - [x] Homepage loading after installation
    - [x] Admin loading after installation (comes to welcome screen)
    - [x] More in-depth testing of admin (try creating a post, etc.)
  - [x] Upgrade from legacy version (eg. `v4.x`)
  - [x] Upgrade from latest master (the flawed `v5.2.2` at 4795e83d27083a0ad3970f5f99425db71148514d)
  - [x] Backup and restore

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by badrihippo** [comment]
Okay, it's been tested to the best of my abilities! @tituspijean I guess you or someone else in the YunoHost organisation needs to run the automated tests? And then I think we'll be ready to merge! :rocket:

**Comment by tituspijean** [comment]
!testme
!bullseyetestme

**Comment by badrihippo** [comment]
Oh no, that annoying `ESOCKETTIMEDOUT` while installing `date-fns`! This apparently happens on slightly slower systems, including mine, and the YunoHost CI seems to be one of them too :persevere:

It's actually a "write to hard-disk" timeout, not a network timeout, and I think it might have been fixed in later Yarn versions but otherwise a common workaround is to increase the network timeout time (see https://github.com/date-fns/date-fns/issues/1004 and https://github.com/yarnpkg/yarn/issues/8242 for example).

Since this will probably come up for many users on low-end YunoHost systems, I've added a command to this script to increase the timeout to 10 minutes. @tituspijean could you run another test? Thanks! :sweat_smile:

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Grmblml...
!testme

**Comment by tituspijean** [comment]
Ooops did not mean to merge-push like that. Anyways, it looks to be working, thank you so much @badrihippo ! ❤️

**Comment by badrihippo** [comment]
Yayy, that's awesome!! Glad I could be of help (and of course that we all have a functioning Ghost!) :grin:

**Pull request merged**
